name: Performance Tests
on:
  pull_request:
    branches:
      - trunk
  push:
    branches:
      - trunk
      - 'feature/**'

jobs:
  # Runs the performance test suite.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up Node.js.
  # - Installs npm dependencies.
  # - Logs Docker debug information (about the Docker installation within the runner).
  # - Builds WordPress to run from the `build` directory.
  # - Starts the WordPress Docker container.
  # - Logs the running Docker containers.
  # - Install WordPress within the Docker container.
  # - Run the Performance tests.
  # - Ensures version-controlled files are not modified or deleted.
  performance:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'mukeshpanchal27/wordpress-develop' || github.event_name == 'push' }}

    steps:
      - name: Configure environment variables
        run: |
          echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
          echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Docker debug information
        run: |
          docker -v
          docker-compose -v

      - name: Build WordPress
        run: npm run build

      - name: Start Docker environment
        run: npm run env:start

      - name: WordPress Docker container debug information
        run: |
          docker-compose run --rm mysql mysql --version
          docker-compose run --rm php php --version
          docker-compose run --rm php php -m
          docker-compose run --rm php php -i
          docker-compose run --rm php locale -a

      - name: Install WordPress
        run: npm run env:install

      - name: Ensure version-controlled files are not modified or deleted
        run: git diff --exit-code
