name: Performance

on:
  pull_request:
    branches:
      - trunk

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use desired version of NodeJS
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install MU plugin
        run: |
          mkdir ./wp-content/mu-plugins
          cp ./tests/performance/mu-plugin.php ./wp-content/mu-plugins/mu-plugin.php

      - name: Set up WP environment
        run: npm run env:start