name: Performance Tests

on:
    pull_request:
      branches:
        - trunk
      # Only run if PHP-related files changed.
      types:
        - opened
        - reopened
        - synchronize
    release:
        types: [published]
    push:
        branches: [trunk]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    performance:
        name: Run performance tests
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'mukeshpanchal27/wordpress-develop' }}

        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

            - name: Use desired version of NodeJS
              uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Npm install
              run: |
                  npm ci
                  
            - name: Compare performance with trunk
              if: github.event_name == 'pull_request'
              run: ./bin/cli.js perf $GITHUB_SHA trunk --tests-branch $GITHUB_SHA
