name: Performance Tests

on:
  push:
    branches:
      - trunk
      - 'feature/**'
      - '3.[7-9]'
      - '[4-9].[0-9]'
    tags:
      - '[0-9]+.[0-9]'
      - '[0-9]+.[0-9].[0-9]+'
  pull_request:
    branches:
      - trunk
      - 'feature/**'
      - '3.[7-9]'
      - '[4-9].[0-9]'

jobs:
  # Runs the performance test suite.
  #
  # Performs the following steps:
  # - Sets environment variables.
  # - Checks out the repository.
  # - Sets up Node.js.
  # - Installs npm dependencies.
  # - Logs Docker debug information (about the Docker installation within the runner).
  # - Builds WordPress to run from the `build` directory.
  # - Starts the WordPress Docker container.
  # - Logs the running Docker containers.
  # - Install WordPress within the Docker container.
  # - Run the Performance tests.
  # - Ensures version-controlled files are not modified or deleted.
  performance:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'mukeshpanchal27/wordpress-develop' || github.event_name == 'push' }}

    steps:
      - name: Configure environment variables
        run: |
          echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
          echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Docker debug information
        run: |
          docker -v
          docker-compose -v

      - name: Compare performance with trunk
        if: github.event_name == 'pull_request'
        run: node ./tests/performance/cli.js perf $GITHUB_SHA trunk --tests-branch $GITHUB_SHA

      - name: Ensure version-controlled files are not modified or deleted
        run: git diff --exit-code