name: Performance

on:
  pull_request:
    branches:
      - trunk

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Set the core version and plugins config 
        run: ./bin/set-wp-config.js --mu-plugin=./bin/mu-plugin

      - name: Set up WP environment
        run: npm run env:start